using System.Text;
using System.Text.Json;

namespace MyShortcutGuide.Core;

/// <summary>PowerToys v0.100+ adapter. Keep schema decisions out of the document model.</summary>
public static class ManifestWriter
{
    public const string FileName = "Local.MyShortcutGuide.en-US.yml";
    public static string Generate(ShortcutDocument document)
    {
        document.Validate();
        var b = new StringBuilder("# Generated by My Shortcut Guide. Edit shortcuts.json through the editor.\n");
        b.AppendLine("PackageName: Local.MyShortcutGuide");
        b.AppendLine("Name: My Shortcuts");
        b.AppendLine("WindowFilter: MyShortcutGuide.exe");
        b.AppendLine("BackgroundProcess: true");
        b.AppendLine(document.Sections.Count == 0 ? "Shortcuts: []" : "Shortcuts:");
        foreach (var section in document.Sections)
        {
            b.AppendLine($"  - SectionName: {Quote(section.Name)}");
            b.AppendLine(section.Shortcuts.Count == 0 ? "    Properties: []" : "    Properties:");
            foreach (var item in section.Shortcuts)
            {
                b.AppendLine($"      - Name: {Quote(item.Name)}");
                b.AppendLine($"        Description: {Quote(item.Description)}");
                b.AppendLine($"        Recommended: {Bool(item.Recommended)}");
                b.AppendLine("        Shortcut:");
                b.AppendLine($"          - Win: {Bool(item.DisplayText is null && item.Win)}");
                b.AppendLine($"            Ctrl: {Bool(item.DisplayText is null && item.Ctrl)}");
                b.AppendLine($"            Shift: {Bool(item.DisplayText is null && item.Shift)}");
                b.AppendLine($"            Alt: {Bool(item.DisplayText is null && item.Alt)}");
                // A zero-width prefix keeps literal numbers, arrow names and <tokens> from being interpreted as keys.
                // This adapter-only marker is not stored in the source JSON.
                b.AppendLine($"            Keys: [{Quote(item.DisplayText is null ? item.KeyCode.ToString(System.Globalization.CultureInfo.InvariantCulture) : "\u200B" + item.DisplayText)}]");
            }
        }
        return b.ToString();
    }
    private static string Bool(bool value) => value ? "true" : "false";
    // JSON double-quoted scalars are valid YAML. This escapes newlines, quotes, colons and Unicode safely.
    private static string Quote(string text) => JsonSerializer.Serialize(text);
    public static void Write(ShortcutDocument document, string directory)
    {
        var path = Path.Combine(directory, FileName);
        if (document.Settings.ShowInShortcutGuide) AtomicFile.Write(path, Generate(document));
        else if (File.Exists(path)) File.Delete(path);
    }
}
